### ISSUE TITLE
Additional rescuers 

### ISSUE THREAD

**Issue by RamiKrispin** [mine-cetinkaya-rundel/covid19-r#1]
Hi @mine-cetinkaya-rundel thanks for creating this page! Could you please add the following two resources:

**covid19italy** package - https://github.com/RamiKrispin/covid19Italy, and [flexdashboard](https://ramikrispin.github.io/coronavirus_dashboard/)

Thx!
Rami

**Comment by mine-cetinkaya-rundel** [comment]
Added, thank you!
