### ISSUE TITLE
Florida COVID-19 Tracking

### ISSUE THREAD

**Issue by gadenbuie** [mine-cetinkaya-rundel/covid19-r#11]
I’ve been tracking and parsing the data released by the Florida DOH at http://github.com/gadenbuie/covid19-florida.

The repo is part historical record of the numbers reported by FLDOH and partly an attempt to coerce the many different reporting modalities into a cleanish data set, and the repo includes a few auto-updated plots.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
