### ISSUE TITLE
Change URL and add 3 resources

### ISSUE THREAD

**Issue by AntoineSoetewey** [mine-cetinkaya-rundel/covid19-r#12]
Dear Mine,

I see that the URL of the post "Top 25 R resources on Novel COVID-19 Coronavirus" redirects to my post on Towards Data Science. Is it possible to change the URL to the original URL? Here it is: https://www.statsandr.com/blog/top-r-resources-on-covid-19-coronavirus/.

Also, is it possible to add:
- this blog post: https://www.statsandr.com/blog/how-to-create-a-simple-coronavirus-dashboard-specific-to-your-country-in-r/
- this blog post: https://www.statsandr.com/blog/covid-19-in-belgium/
- and this dashboard: https://www.antoinesoetewey.com/files/coronavirus-dashboard.html. The code can be found here: https://github.com/AntoineSoetewey/coronavirus_dashboard

Thanks in advance!
Best,
Antoine

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
