### ISSUE TITLE
Yet another Covid-19 package: {tidycovid19}

### ISSUE THREAD

**Issue by joachim-gassen** [mine-cetinkaya-rundel/covid19-r#14]
Dear Mine: 

Thank you for maintaining this fine list. Very helpful! Thank you as well for including some of my recent blog posts. This is just to let you know that I published a new Covid-19 related package that provides download functions for various data sources, including data on governmental interventions along with a flexible visualization tool and an accompanying shiny app.

https://github.com/joachim-gassen/tidycovid19

I would appreciate if you could include it in the list but of course, no pressure intended.

Cheers, 
Joachim

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, adding now!

**Comment by joachim-gassen** [comment]
Thanks!
