### ISSUE TITLE
Shiny App for India

### ISSUE THREAD

**Issue by srinathkr07** [mine-cetinkaya-rundel/covid19-r#19]
I would like to submit my Shiny app made for India. 

https://srinathkr.shinyapps.io/COVID19-India/

**Comment by mine-cetinkaya-rundel** [comment]
Hi! Happy to add, however the app is giving me an error right now. Would you let me know when it's running. Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Seems to be working now, added to the list, thank you!

**Comment by srinathkr07** [comment]
Thank you!
