### ISSUE TITLE
Teaching resource for beginners learning data science with Covid-19 data

### ISSUE THREAD

**Issue by lukas-jue** [mine-cetinkaya-rundel/covid19-r#20]
Hi @mine-cetinkaya-rundel,
Great repository! Lots of interesting links! I'd like to contribute a relatively comprehensive educational resource that we've developed:
https://lukas-jue.github.io/data-science-covid-guide/
We're a student-run non-profit called TechAcademy and located at Goethe University in Frankfurt, Germany. Our aim is to make coding and data science more accessible to non-computer science students.
This project guide is mostly aimed at beginners and part of a voluntary single semester blended learning course in data science (50% online courses, 50% this project in small teams). In this project guide, we're providing code examples and explanations in both R and Python - our students pick one of them in the beginning.
Hope this is helpful!

**Comment by mine-cetinkaya-rundel** [comment]
This is fantastic, thank you so much for sharing!
