### ISSUE TITLE
PredictPandemic.org

### ISSUE THREAD

**Issue by Alessandro-Rabiolo** [mine-cetinkaya-rundel/covid19-r#23]
Hello
I want to bring to your attention also the dashboard https://predictpandemic.org, which provides an interactive framework to study the relationship between Google Trends of COVID-19 symptoms and the ongoing epidemic. 
The code of the application were posted in the Zenodo repository (https://zenodo.org/record/4603713#.YHsl9i1Q1QI)
Thank you for your good work
Best
Alessandro Rabiolo

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, I added it!

**Comment by Alessandro-Rabiolo** [comment]
Great!
Thank you
