### ISSUE TITLE
A new covid dashboard

### ISSUE THREAD

**Issue by endri81** [mine-cetinkaya-rundel/covid19-r#25]
Hi,
I want to propose a dashboard I developed to compare covid19 situation in Balkan countries. Regards

https://endriraco.shinyapps.io/CovidBalkans/

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the submission. The app doesn't seem to be live anymore.

**Comment by endri81** [comment]
Sorry, you are totally right. The link was changed to 
https://endriraco.shinyapps.io/BalkanCovidSituation/
due to paper publication.
Thank you
