### ISSUE TITLE
Code and materials for two COVID papers written in R

### ISSUE THREAD

**Issue by mpjashby** [mine-cetinkaya-rundel/covid19-r#26]
I’m not sure if this is what you’re looking for, but I’ve written two papers on how COVID affected crime and demand for police, both focused on the early months of the pandemic. R code and other materials are available on GitHub:

*  [COVID and crime](https://github.com/mpjashby/covid19-crime)
* [COVID and police demand](https://github.com/mpjashby/covid19-calls)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
